apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qm9hg5kqx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qm9hg5kqx-go 
  name: qm9hg5kqx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qm9hg5kqx-go 
